export interface JainWord {
  word: string;
  eng: string;
  hi: string;
  karma: number;
  emoji: string;
  level: 1|2|3;
  color: string;
  category: string;
}

export const JAIN_WORDS: JainWord[] = [
  // ── LEVEL 1 – Basic Jain terms ──────────────────────────────
  {word:"जीव",eng:"Soul",hi:"आत्मा का अस्तित्व।",karma:10,emoji:"✨",level:1,color:"#4CAF50",category:"soul"},
  {word:"कर्म",eng:"Karma",hi:"हर कर्म का फल मिलता है।",karma:12,emoji:"⚖️",level:1,color:"#FF9800",category:"karma"},
  {word:"दान",eng:"Charity",hi:"दान से आत्मा शुद्ध होती है।",karma:15,emoji:"💝",level:1,color:"#E91E63",category:"virtue"},
  {word:"तप",eng:"Austerity",hi:"तप से पुराने कर्म जलते हैं।",karma:12,emoji:"🔥",level:1,color:"#FF5722",category:"practice"},
  {word:"धर्म",eng:"Righteousness",hi:"सही आचरण ही धर्म है।",karma:15,emoji:"🙏",level:1,color:"#9C27B0",category:"virtue"},
  {word:"सत्य",eng:"Truth",hi:"सत्य बोलना सबसे बड़ा धर्म है।",karma:15,emoji:"✅",level:1,color:"#2196F3",category:"virtue"},
  {word:"दया",eng:"Compassion",hi:"दया ही धर्म की जड़ है।",karma:15,emoji:"💙",level:1,color:"#00BCD4",category:"virtue"},
  {word:"पाप",eng:"Sin",hi:"बुरे कर्म से पाप लगता है।",karma:10,emoji:"⚫",level:1,color:"#607D8B",category:"karma"},
  {word:"पुण्य",eng:"Merit",hi:"अच्छे कर्म से पुण्य मिलता है।",karma:15,emoji:"⭐",level:1,color:"#FFD700",category:"karma"},
  {word:"राग",eng:"Attachment",hi:"राग से बंधन होता है।",karma:10,emoji:"🔗",level:1,color:"#F44336",category:"kashaya"},
  {word:"द्वेष",eng:"Hatred",hi:"द्वेष से कर्म बंधन होता है।",karma:10,emoji:"💢",level:1,color:"#E91E63",category:"kashaya"},
  {word:"मोह",eng:"Delusion",hi:"मोह आत्मा को अंधा करता है।",karma:10,emoji:"😵",level:1,color:"#9C27B0",category:"kashaya"},
  {word:"लोभ",eng:"Greed",hi:"लोभ से दुःख मिलता है।",karma:10,emoji:"💰",level:1,color:"#FF9800",category:"kashaya"},
  {word:"क्रोध",eng:"Anger",hi:"क्रोध से आत्मा जलती है।",karma:10,emoji:"😤",level:1,color:"#F44336",category:"kashaya"},
  {word:"मान",eng:"Pride",hi:"अहंकार से पतन होता है।",karma:10,emoji:"😤",level:1,color:"#FF5722",category:"kashaya"},
  {word:"माया",eng:"Deceit",hi:"माया से जीव भटकता है।",karma:10,emoji:"🎭",level:1,color:"#9C27B0",category:"kashaya"},
  {word:"बंध",eng:"Bondage",hi:"कर्म से आत्मा बंधती है।",karma:10,emoji:"⛓️",level:1,color:"#607D8B",category:"karma"},
  {word:"सुख",eng:"Happiness",hi:"पुण्य कर्म से सुख मिलता है।",karma:10,emoji:"😊",level:1,color:"#4CAF50",category:"general"},
  {word:"दुःख",eng:"Sorrow",hi:"पाप कर्म से दुःख मिलता है।",karma:10,emoji:"😢",level:1,color:"#607D8B",category:"general"},
  {word:"भाव",eng:"Intention",hi:"भाव से कर्म बनता है।",karma:12,emoji:"💭",level:1,color:"#2196F3",category:"karma"},
  {word:"बोध",eng:"Awakening",hi:"बोध से आत्मज्ञान होता है।",karma:12,emoji:"💡",level:1,color:"#FFD700",category:"knowledge"},
  {word:"शुभ",eng:"Auspicious",hi:"शुभ कार्य से पुण्य मिलता है।",karma:12,emoji:"🌸",level:1,color:"#4CAF50",category:"virtue"},
  {word:"सेवा",eng:"Service",hi:"सेवा से कर्म कटता है।",karma:15,emoji:"🤝",level:1,color:"#00BCD4",category:"virtue"},
  {word:"विनय",eng:"Humility",hi:"विनय से ज्ञान बढ़ता है।",karma:12,emoji:"🙏",level:1,color:"#9C27B0",category:"virtue"},
  {word:"क्षमा",eng:"Forgiveness",hi:"क्षमा सबसे बड़ा बल है।",karma:20,emoji:"💝",level:1,color:"#E91E63",category:"virtue"},
  {word:"शांति",eng:"Peace",hi:"शांति से आत्मा निर्मल होती है।",karma:15,emoji:"☮️",level:1,color:"#00BCD4",category:"virtue"},
  {word:"तीर्थ",eng:"Sacred site",hi:"तीर्थ यात्रा से पुण्य मिलता है।",karma:12,emoji:"🕌",level:1,color:"#FF9800",category:"jain"},
  {word:"मुनि",eng:"Monk",hi:"मुनि सभी प्रपंच छोड़ते हैं।",karma:15,emoji:"🧘",level:1,color:"#795548",category:"jain"},
  {word:"गुरु",eng:"Teacher",hi:"सच्चे गुरु मोक्ष का मार्ग दिखाते हैं।",karma:15,emoji:"📿",level:1,color:"#FF5722",category:"jain"},
  {word:"अहिंसा",eng:"Non-violence",hi:"किसी जीव को न सताओ।",karma:25,emoji:"🕊️",level:1,color:"#4CAF50",category:"vow"},
  {word:"अरिहंत",eng:"Arihant",hi:"जिन्होंने राग-द्वेष जीत लिया।",karma:20,emoji:"🌟",level:1,color:"#FFD700",category:"navkar"},
  {word:"सिद्ध",eng:"Siddha",hi:"पूर्ण मुक्त आत्मा।",karma:20,emoji:"✨",level:1,color:"#FFD700",category:"navkar"},
  {word:"साधु",eng:"Sadhu",hi:"सभी वस्तुओं का त्याग करने वाले।",karma:15,emoji:"🧘",level:1,color:"#795548",category:"navkar"},
  {word:"जिन",eng:"Jina",hi:"जिन्होंने इंद्रियों को जीत लिया।",karma:20,emoji:"🌸",level:1,color:"#FFD700",category:"jain"},
  {word:"नवकार",eng:"Navkar Mantra",hi:"जैन धर्म की सर्वोच्च प्रार्थना।",karma:30,emoji:"📿",level:1,color:"#9C27B0",category:"navkar"},
  {word:"समायिक",eng:"Samayik",hi:"समायिक ध्यान साधना।",karma:20,emoji:"🧘",level:1,color:"#2196F3",category:"practice"},
  {word:"उपवास",eng:"Fasting",hi:"उपवास से तप होता है।",karma:15,emoji:"🌿",level:1,color:"#4CAF50",category:"practice"},
  {word:"पर्युषण",eng:"Paryushana",hi:"8 दिन का पर्युषण पर्व।",karma:20,emoji:"🌺",level:1,color:"#E91E63",category:"festival"},
  {word:"मिच्छामि",eng:"Micchami Dukkadam",hi:"क्षमा प्रार्थना।",karma:20,emoji:"🙏",level:1,color:"#FF9800",category:"festival"},
  {word:"स्वर्ग",eng:"Heaven",hi:"पुण्य से स्वर्ग मिलता है।",karma:12,emoji:"☁️",level:1,color:"#2196F3",category:"general"},
  {word:"नरक",eng:"Hell",hi:"पाप से नरक में जाना होता है।",karma:10,emoji:"🔥",level:1,color:"#F44336",category:"general"},
  {word:"मनुष्य",eng:"Human",hi:"मनुष्य जन्म सबसे दुर्लभ है।",karma:12,emoji:"👤",level:1,color:"#795548",category:"general"},
  {word:"आत्मा",eng:"Soul",hi:"आत्मा अजर अमर है।",karma:15,emoji:"✨",level:1,color:"#FFD700",category:"soul"},
  {word:"मोक्ष",eng:"Liberation",hi:"मोक्ष परम लक्ष्य है।",karma:25,emoji:"🌟",level:1,color:"#FFD700",category:"moksha"},
  {word:"जीवन",eng:"Life",hi:"जीवन अनमोल है।",karma:12,emoji:"🌱",level:1,color:"#4CAF50",category:"general"},
  {word:"ध्यान",eng:"Meditation",hi:"ध्यान से आत्मशांति मिलती है।",karma:20,emoji:"🧘",level:1,color:"#9C27B0",category:"practice"},
  {word:"आगम",eng:"Scripture",hi:"जैन आगम पवित्र ग्रंथ हैं।",karma:15,emoji:"📖",level:1,color:"#795548",category:"scripture"},
  {word:"भक्ति",eng:"Devotion",hi:"भक्ति से मन शुद्ध होता है।",karma:15,emoji:"🌸",level:1,color:"#E91E63",category:"virtue"},
  {word:"तृष्णा",eng:"Craving",hi:"तृष्णा से दुःख मिलता है।",karma:10,emoji:"💧",level:1,color:"#F44336",category:"kashaya"},
  {word:"निर्मल",eng:"Pure",hi:"निर्मल आत्मा मोक्ष पाती है।",karma:15,emoji:"✨",level:1,color:"#4CAF50",category:"soul"},
  {word:"दोष",eng:"Fault",hi:"दोषों से मुक्त होना जरूरी है।",karma:10,emoji:"❌",level:1,color:"#F44336",category:"karma"},
  {word:"त्याग",eng:"Renunciation",hi:"त्याग से आत्मा मुक्त होती है।",karma:20,emoji:"🌿",level:1,color:"#4CAF50",category:"virtue"},
  {word:"प्रेम",eng:"Love",hi:"निःस्वार्थ प्रेम पुण्य बढ़ाता है।",karma:15,emoji:"❤️",level:1,color:"#E91E63",category:"virtue"},
  {word:"श्रद्धा",eng:"Faith",hi:"सच्ची श्रद्धा मोक्ष की नींव।",karma:15,emoji:"🙏",level:1,color:"#FF5722",category:"virtue"},
  {word:"वैराग्य",eng:"Detachment",hi:"सांसारिक वस्तुओं से दूरी।",karma:20,emoji:"🌿",level:1,color:"#795548",category:"virtue"},
  {word:"साधना",eng:"Spiritual practice",hi:"नित्य साधना से उन्नति होती है।",karma:20,emoji:"🧘",level:1,color:"#9C27B0",category:"practice"},
  {word:"पूजा",eng:"Worship",hi:"जिनेंद्र पूजा से पुण्य मिलता है।",karma:15,emoji:"🌸",level:1,color:"#E91E63",category:"practice"},
  {word:"स्वाध्याय",eng:"Self-study",hi:"स्वाध्याय से ज्ञान बढ़ता है।",karma:20,emoji:"📚",level:1,color:"#2196F3",category:"practice"},
  {word:"संयम",eng:"Self-restraint",hi:"संयम से कर्म नहीं बंधते।",karma:20,emoji:"🧘",level:1,color:"#7C4DFF",category:"virtue"},
  {word:"करुणा",eng:"Compassion",hi:"करुणा से पुण्य बढ़ता है।",karma:20,emoji:"💙",level:1,color:"#2196F3",category:"virtue"},
  {word:"समता",eng:"Equanimity",hi:"सुख-दुख में समान रहना।",karma:20,emoji:"⚖️",level:1,color:"#00BCD4",category:"virtue"},
  {word:"मैत्री",eng:"Friendship",hi:"सभी जीवों से मित्रता।",karma:20,emoji:"🤝",level:1,color:"#4CAF50",category:"virtue"},
  {word:"चरित्र",eng:"Character",hi:"अच्छा चरित्र मोक्ष का मार्ग है।",karma:20,emoji:"⭐",level:1,color:"#FF9800",category:"virtue"},
  // 60 words level 1 so far
  // ── LEVEL 2 – Intermediate ──────────────────────────────────
  {word:"अपरिग्रह",eng:"Non-possessiveness",hi:"जरूरत से ज्यादा मत रखो।",karma:30,emoji:"🌿",level:2,color:"#4CAF50",category:"vow"},
  {word:"ब्रह्मचर्य",eng:"Celibacy",hi:"इंद्रियों पर पूर्ण नियंत्रण।",karma:25,emoji:"🌸",level:2,color:"#9C27B0",category:"vow"},
  {word:"अस्तेय",eng:"Non-stealing",hi:"किसी की वस्तु मत लो।",karma:25,emoji:"✋",level:2,color:"#2196F3",category:"vow"},
  {word:"केवलज्ञान",eng:"Omniscience",hi:"परम ज्ञान — सब कुछ जानना।",karma:50,emoji:"💫",level:2,color:"#FF9800",category:"knowledge"},
  {word:"निर्वाण",eng:"Nirvana",hi:"मोक्ष की अवस्था — परम शांति।",karma:30,emoji:"☀️",level:2,color:"#FFD700",category:"moksha"},
  {word:"निर्जरा",eng:"Shedding of karma",hi:"कर्मों का नाश।",karma:25,emoji:"✨",level:2,color:"#4CAF50",category:"karma"},
  {word:"संवर",eng:"Stopping karma",hi:"नए कर्मों का आना रोकना।",karma:25,emoji:"🛡️",level:2,color:"#2196F3",category:"karma"},
  {word:"आश्रव",eng:"Influx of karma",hi:"नए कर्मों का आगमन।",karma:15,emoji:"🌊",level:2,color:"#F44336",category:"karma"},
  {word:"अष्टकर्म",eng:"Eight karmas",hi:"आठ प्रकार के कर्म।",karma:30,emoji:"⛓️",level:2,color:"#607D8B",category:"karma"},
  {word:"सम्यग्दर्शन",eng:"Right faith",hi:"सच्ची श्रद्धा ही मोक्ष का मार्ग।",karma:30,emoji:"👁️",level:2,color:"#FFD700",category:"ratnatraya"},
  {word:"सम्यग्ज्ञान",eng:"Right knowledge",hi:"सच्चा ज्ञान आत्मा को जानना है।",karma:30,emoji:"📖",level:2,color:"#2196F3",category:"ratnatraya"},
  {word:"आत्मज्ञान",eng:"Self-knowledge",hi:"स्वयं को जानना ही सच्चा ज्ञान।",karma:30,emoji:"💡",level:2,color:"#9C27B0",category:"knowledge"},
  {word:"परमार्थ",eng:"Ultimate truth",hi:"परम सत्य का ज्ञान।",karma:25,emoji:"🔮",level:2,color:"#7C4DFF",category:"philosophy"},
  {word:"द्रव्यसंग्रह",eng:"Compendium of substances",hi:"नेमिचंद्र का ग्रंथ।",karma:30,emoji:"📚",level:2,color:"#795548",category:"scripture"},
  {word:"तत्त्वार्थ",eng:"Tattvartha",hi:"जैन दर्शन का सार।",karma:30,emoji:"📜",level:2,color:"#9C27B0",category:"scripture"},
  {word:"तीर्थंकर",eng:"Tirthankar",hi:"मोक्ष मार्ग दिखाने वाले।",karma:50,emoji:"🌈",level:2,color:"#FFD700",category:"jain"},
  {word:"महावीर",eng:"Mahavir",hi:"24वें तीर्थंकर — अहिंसा के प्रचारक।",karma:40,emoji:"🦚",level:2,color:"#FFD700",category:"tirthankar"},
  {word:"ऋषभदेव",eng:"Rishabhdeva",hi:"पहले तीर्थंकर।",karma:35,emoji:"🌟",level:2,color:"#FF9800",category:"tirthankar"},
  {word:"नेमिनाथ",eng:"Neminath",hi:"22वें तीर्थंकर।",karma:30,emoji:"🌸",level:2,color:"#E91E63",category:"tirthankar"},
  {word:"पार्श्वनाथ",eng:"Parshvanath",hi:"23वें तीर्थंकर।",karma:35,emoji:"🐍",level:2,color:"#4CAF50",category:"tirthankar"},
  {word:"परमेष्ठी",eng:"Supreme being",hi:"पाँच परम पूज्य।",karma:30,emoji:"⭐",level:2,color:"#FFD700",category:"jain"},
  {word:"गुणस्थान",eng:"Soul stages",hi:"आत्मा के 14 विकास के चरण।",karma:30,emoji:"📊",level:2,color:"#9C27B0",category:"philosophy"},
  {word:"लेश्या",eng:"Soul coloring",hi:"आत्मा के भाव-रंग।",karma:25,emoji:"🎨",level:2,color:"#E91E63",category:"philosophy"},
  {word:"कषाय",eng:"Passions",hi:"क्रोध मान माया लोभ — चार कषाय।",karma:20,emoji:"🔥",level:2,color:"#F44336",category:"kashaya"},
  {word:"स्यादवाद",eng:"Syadvada",hi:"शायद — अनेकांत का प्रयोग।",karma:30,emoji:"💭",level:2,color:"#7C4DFF",category:"philosophy"},
  {word:"प्रतिक्रमण",eng:"Pratikraman",hi:"पापों से माफी माँगना।",karma:20,emoji:"🙏",level:2,color:"#FF5722",category:"practice"},
  {word:"सर्वज्ञता",eng:"Omniscience",hi:"सब जानने की शक्ति।",karma:35,emoji:"💫",level:2,color:"#FFD700",category:"knowledge"},
  {word:"दिगंबर",eng:"Digambar sect",hi:"वस्त्र रहित मुनि परंपरा।",karma:20,emoji:"🧘",level:2,color:"#795548",category:"jain"},
  {word:"श्वेतांबर",eng:"Shvetambar sect",hi:"सफेद वस्त्र धारण करने वाले।",karma:20,emoji:"🤍",level:2,color:"#607D8B",category:"jain"},
  {word:"आचार्य",eng:"Acharya",hi:"जैन संघ के प्रमुख।",karma:20,emoji:"📿",level:2,color:"#9C27B0",category:"navkar"},
  {word:"उपाध्याय",eng:"Upadhyay",hi:"जैन शास्त्रों के शिक्षक।",karma:20,emoji:"📚",level:2,color:"#2196F3",category:"navkar"},
  {word:"अनेकांत",eng:"Many-sidedness",hi:"सत्य के अनेक पहलू होते हैं।",karma:25,emoji:"🔮",level:2,color:"#9C27B0",category:"philosophy"},
  {word:"कल्याणक",eng:"Auspicious events",hi:"तीर्थंकर के पाँच कल्याणक।",karma:25,emoji:"🌟",level:2,color:"#FFD700",category:"jain"},
  {word:"सम्मेदशिखर",eng:"Sammed Shikhar",hi:"जैन तीर्थ — झारखंड।",karma:30,emoji:"⛰️",level:2,color:"#4CAF50",category:"jain"},
  {word:"पालीताना",eng:"Palitana",hi:"गुजरात का महान जैन तीर्थ।",karma:25,emoji:"🕌",level:2,color:"#FF9800",category:"jain"},
  {word:"श्रवणबेलगोला",eng:"Shravanabelagola",hi:"बाहुबली की विशाल प्रतिमा।",karma:25,emoji:"🗿",level:2,color:"#795548",category:"jain"},
  {word:"बाहुबली",eng:"Bahubali",hi:"ऋषभदेव के पुत्र — पहले दिगंबर मुनि।",karma:25,emoji:"💪",level:2,color:"#FF9800",category:"jain"},
  {word:"अष्टाप्रकारी",eng:"Eightfold worship",hi:"आठ प्रकार से पूजा।",karma:25,emoji:"🌸",level:2,color:"#E91E63",category:"practice"},
  {word:"विसर्जन",eng:"Immersion",hi:"मूर्ति विसर्जन की परंपरा।",karma:15,emoji:"🌊",level:2,color:"#2196F3",category:"practice"},
  {word:"चतुर्विध",eng:"Fourfold",hi:"चतुर्विध संघ — मुनि आर्यिका श्रावक श्राविका।",karma:25,emoji:"👥",level:2,color:"#9C27B0",category:"jain"},
  {word:"महाव्रत",eng:"Great vows",hi:"मुनियों के पाँच महाव्रत।",karma:30,emoji:"⭐",level:2,color:"#FF9800",category:"vow"},
  {word:"अणुव्रत",eng:"Minor vows",hi:"श्रावकों के पाँच अणुव्रत।",karma:25,emoji:"🌱",level:2,color:"#4CAF50",category:"vow"},
  {word:"प्रमोद",eng:"Joy in others good",hi:"दूसरों की खुशी में खुश होना।",karma:20,emoji:"😊",level:2,color:"#FFD700",category:"virtue"},
  {word:"माध्यस्थ",eng:"Equanimity",hi:"सब के प्रति समभाव रखना।",karma:20,emoji:"⚖️",level:2,color:"#607D8B",category:"virtue"},
  {word:"जिनालय",eng:"Jain temple",hi:"जिनालय में जिनेंद्र विराजते हैं।",karma:20,emoji:"🕌",level:2,color:"#FF9800",category:"jain"},
  {word:"उत्सर्ग",eng:"Abandonment",hi:"सब कुछ छोड़ देने का भाव।",karma:20,emoji:"🌿",level:2,color:"#4CAF50",category:"virtue"},
  {word:"पंचेन्द्रिय",eng:"Five-sensed being",hi:"पाँच इंद्रियों से युक्त जीव।",karma:15,emoji:"👁️",level:2,color:"#2196F3",category:"philosophy"},
  {word:"चैतन्य",eng:"Consciousness",hi:"आत्मा का मूल लक्षण।",karma:25,emoji:"💡",level:2,color:"#FFD700",category:"soul"},
  {word:"अध्यात्म",eng:"Spirituality",hi:"आत्म-साधना का विज्ञान।",karma:25,emoji:"✨",level:2,color:"#9C27B0",category:"soul"},
  {word:"विपाक",eng:"Fruition of karma",hi:"कर्मों का फल पकना।",karma:20,emoji:"🍎",level:2,color:"#FF9800",category:"karma"},
  {word:"उदय",eng:"Rising of karma",hi:"कर्मों का उदय।",karma:15,emoji:"🌅",level:2,color:"#FF5722",category:"karma"},
  {word:"सत्तासत्",eng:"Real existence",hi:"सत् — जो है वह सत् है।",karma:20,emoji:"🌐",level:2,color:"#607D8B",category:"philosophy"},
  {word:"गृहस्थ",eng:"Householder",hi:"गृहस्थ भी धर्म पाल सकता है।",karma:15,emoji:"🏠",level:2,color:"#795548",category:"jain"},
  {word:"श्रावक",eng:"Lay follower",hi:"श्रावक जैन धर्म का पालन करता है।",karma:20,emoji:"🙏",level:2,color:"#FF9800",category:"jain"},
  {word:"आर्यिका",eng:"Nun",hi:"महिला दीक्षित साध्वी।",karma:20,emoji:"🧘",level:2,color:"#E91E63",category:"jain"},
  {word:"मुक्तात्मा",eng:"Liberated soul",hi:"कर्म रहित शुद्ध आत्मा।",karma:30,emoji:"🌟",level:2,color:"#FFD700",category:"moksha"},
  {word:"अलोक",eng:"Non-universe",hi:"लोक के बाहर का स्थान।",karma:15,emoji:"🌌",level:2,color:"#1a237e",category:"philosophy"},
  {word:"तिर्यंच",eng:"Animal/plant beings",hi:"पशु पक्षी वनस्पति — तिर्यंच गति।",karma:12,emoji:"🦋",level:2,color:"#4CAF50",category:"philosophy"},
  {word:"देवगति",eng:"Heavenly realm",hi:"देव लोक में जाना।",karma:15,emoji:"☁️",level:2,color:"#2196F3",category:"philosophy"},
  {word:"नरकगति",eng:"Hellish realm",hi:"नरक लोक में जाना।",karma:12,emoji:"🔥",level:2,color:"#F44336",category:"philosophy"},
  {word:"संस्कार",eng:"Purification rites",hi:"धार्मिक संस्कार।",karma:15,emoji:"🌸",level:2,color:"#E91E63",category:"practice"},
  {word:"स्वभावधर्म",eng:"Nature-religion",hi:"आत्मा का स्वभाव ही धर्म है।",karma:25,emoji:"✨",level:2,color:"#9C27B0",category:"philosophy"},
  // ── LEVEL 3 – Advanced ──────────────────────────────────────
  {word:"ज्ञानावरणीय",eng:"Knowledge-obscuring karma",hi:"ज्ञान को रोकने वाला कर्म।",karma:40,emoji:"📖",level:3,color:"#7C4DFF",category:"karma"},
  {word:"दर्शनावरणीय",eng:"Perception-obscuring karma",hi:"दर्शन को रोकने वाला कर्म।",karma:40,emoji:"👁️",level:3,color:"#9C27B0",category:"karma"},
  {word:"मोहनीयकर्म",eng:"Deluding karma",hi:"मोह उत्पन्न करने वाला कर्म।",karma:35,emoji:"😵",level:3,color:"#F44336",category:"karma"},
  {word:"अंतरायकर्म",eng:"Obstructing karma",hi:"शक्तियों को रोकने वाला कर्म।",karma:35,emoji:"🚫",level:3,color:"#607D8B",category:"karma"},
  {word:"वेदनीयकर्म",eng:"Feeling-producing karma",hi:"सुख-दुख उत्पन्न करने वाला कर्म।",karma:35,emoji:"❤️",level:3,color:"#E91E63",category:"karma"},
  {word:"पंचपरमेष्ठी",eng:"Five supreme beings",hi:"अरिहंत सिद्ध आचार्य उपाध्याय साधु।",karma:50,emoji:"⭐",level:3,color:"#FFD700",category:"navkar"},
  {word:"सम्यक्चारित्र",eng:"Right conduct",hi:"सही आचरण ही मुक्ति देता है।",karma:40,emoji:"🛤️",level:3,color:"#4CAF50",category:"ratnatraya"},
  {word:"तत्त्वार्थसूत्र",eng:"Tattvartha Sutra",hi:"उमास्वामी का महत्वपूर्ण ग्रंथ।",karma:50,emoji:"📚",level:3,color:"#FF9800",category:"scripture"},
  {word:"षट्खंडागम",eng:"Shatkhandagam",hi:"दिगंबर जैन का प्रमुख ग्रंथ।",karma:45,emoji:"📖",level:3,color:"#795548",category:"scripture"},
  {word:"समयसार",eng:"Samaysara",hi:"आचार्य कुंदकुंद का ग्रंथ।",karma:45,emoji:"📜",level:3,color:"#9C27B0",category:"scripture"},
  {word:"मोक्षमार्ग",eng:"Path to liberation",hi:"मोक्ष का सच्चा मार्ग।",karma:45,emoji:"🛤️",level:3,color:"#FFD700",category:"moksha"},
  {word:"अनंतचतुष्टय",eng:"Four infinities",hi:"अनंत ज्ञान दर्शन सुख शक्ति।",karma:50,emoji:"∞",level:3,color:"#FFD700",category:"soul"},
  {word:"चौदहगुणस्थान",eng:"Fourteen soul stages",hi:"आत्मा के विकास के 14 चरण।",karma:45,emoji:"📊",level:3,color:"#9C27B0",category:"philosophy"},
  {word:"परमात्मस्वरूप",eng:"Supreme soul nature",hi:"परमात्मा का स्वरूप।",karma:50,emoji:"☀️",level:3,color:"#FFD700",category:"soul"},
  {word:"सल्लेखना",eng:"Voluntary death",hi:"मृत्यु का स्वेच्छा से वरण।",karma:40,emoji:"🌿",level:3,color:"#4CAF50",category:"practice"},
  {word:"निश्चयनय",eng:"Absolute standpoint",hi:"परम दृष्टि से देखना।",karma:35,emoji:"🎯",level:3,color:"#7C4DFF",category:"philosophy"},
  {word:"व्यवहारनय",eng:"Practical standpoint",hi:"व्यावहारिक दृष्टि से देखना।",karma:35,emoji:"🌐",level:3,color:"#2196F3",category:"philosophy"},
  {word:"आत्मशुद्धि",eng:"Soul purification",hi:"आत्मा को शुद्ध करने की प्रक्रिया।",karma:40,emoji:"✨",level:3,color:"#4CAF50",category:"soul"},
  {word:"कर्मबंधन",eng:"Karmic bondage",hi:"आत्मा का कर्मों से बंधना।",karma:35,emoji:"⛓️",level:3,color:"#607D8B",category:"karma"},
  {word:"परमानंद",eng:"Supreme bliss",hi:"मोक्ष की अवस्था में परमानंद।",karma:50,emoji:"🌟",level:3,color:"#FFD700",category:"moksha"},
];

export function getWordsByLevel(level: 1|2|3): JainWord[] {
  return JAIN_WORDS.filter(w => w.level === level);
}

export function getRandomWords(level: 1|2|3, count: number): JainWord[] {
  const pool = getWordsByLevel(level);
  return [...pool].sort(() => Math.random()-0.5).slice(0, Math.min(count, pool.length));
}
