export interface GameMeta {
  id: string;
  title: string;
  titleHi: string;
  desc: string;
  emoji: string;
  color: string;
  bg: string;
  age: string;
  players: string;
  available: boolean;
  comingSoon?: string;
  value: string; // Jain value taught
  difficulty: 1 | 2 | 3;
}

export const GAMES: GameMeta[] = [
  {
    id: "snakes-ladders",
    title: "Karma Snakes & Ladders",
    titleHi: "कर्म साँप-सीढ़ी",
    desc: "Land on virtue squares to climb — anger and greed bring you down! Every special square triggers a Jain moral story.",
    emoji: "🎲",
    color: "#4CAF50",
    bg: "linear-gradient(135deg,#1a3a00,#2d5c00)",
    age: "5+",
    players: "1–4",
    available: true,
    value: "Karma & Virtue",
    difficulty: 1,
  },
  {
    id: "memory-quest",
    title: "Navkar Memory Quest",
    titleHi: "नवकार मेमोरी खेल",
    desc: "Match Jain symbols, Tirthankaras, and sacred concepts. Train your mind while learning Jain wisdom!",
    emoji: "🧩",
    color: "#9C27B0",
    bg: "linear-gradient(135deg,#1a0035,#2d0055)",
    age: "4+",
    players: "1",
    available: true,
    value: "Concentration & Knowledge",
    difficulty: 1,
  },
  {
    id: "daily-karma",
    title: "Daily Karma Challenges",
    titleHi: "दैनिक कर्म चुनौती",
    desc: "Complete daily good deeds — feed birds, help parents, speak kindly. Earn badges and grow your karma garden!",
    emoji: "⭐",
    color: "#FF9800",
    bg: "linear-gradient(135deg,#3a1a00,#5c2d00)",
    age: "4+",
    players: "1",
    available: true,
    value: "Daily Practice",
    difficulty: 1,
  },
  {
    id: "tiny-rescue",
    title: "Tiny Life Rescue",
    titleHi: "जीव बचाओ",
    desc: "Rescue ants, butterflies, and birds from danger! Every life saved earns Compassion Stars.",
    emoji: "🦋",
    color: "#00BCD4",
    bg: "linear-gradient(135deg,#001a22,#00303d)",
    age: "4+",
    players: "1",
    available: true,
    value: "Ahimsa",
    difficulty: 2,
  },
  {
    id: "karma-garden",
    title: "Karma Garden",
    titleHi: "कर्म बगीचा",
    desc: "Grow your magical garden with good deeds! Flowers, peacocks, lotus ponds and rainbows unlock as you progress.",
    emoji: "🌸",
    color: "#E91E63",
    bg: "linear-gradient(135deg,#2d0020,#500040)",
    age: "4+",
    players: "1",
    available: true,
    value: "Good Karma",
    difficulty: 1,
  },
  {
    id: "temptation-run",
    title: "Temptation Run",
    titleHi: "प्रलोभन दौड़",
    desc: "Run toward the temple while avoiding temptations! Dodge anger, greed and ego — let your soul glow brighter!",
    emoji: "🏔️",
    color: "#FF5722",
    bg: "linear-gradient(135deg,#2d0a00,#4a1500)",
    age: "6+",
    players: "1",
    available: true,
    value: "Self-Control",
    difficulty: 2,
  },
  {
    id: "aparigraha",
    title: "Aparigraha Adventure",
    titleHi: "अपरिग्रह यात्रा",
    desc: "Explore beautiful forests — but collect too much and your backpack weighs you down! Travel light, travel free.",
    emoji: "🎒",
    color: "#795548",
    bg: "linear-gradient(135deg,#1a0e00,#2d1800)",
    age: "7+",
    players: "1",
    available: true,
    value: "Aparigraha",
    difficulty: 3,
  },
  {
    id: "karma-ludo",
    title: "Karma Ludo",
    titleHi: "कर्म लूडो",
    desc: "Ludo reimagined! Win by both reaching the finish AND earning the most Karma Points through kind choices.",
    emoji: "🎯",
    color: "#2196F3",
    bg: "linear-gradient(135deg,#00103d,#001a5c)",
    age: "6+",
    players: "2–4",
    available: true,
    value: "Multiple Values",
    difficulty: 2,
  },
  {
    id: "compassion-city",
    title: "Compassion City",
    titleHi: "करुणा नगर",
    desc: "Help people, animals, and nature transform a sad city into a joyful, green, beautiful place!",
    emoji: "🏙️",
    color: "#00BCD4",
    bg: "linear-gradient(135deg,#001a20,#002d35)",
    age: "7+",
    players: "1",
    available: true,
    value: "Compassion",
    difficulty: 2,
  },
  {
    id: "jain-stories",
    title: "Jain Story Adventures",
    titleHi: "जैन कथा",
    desc: "Choose your own adventure! Stories of Mahavir, Chandanbala, King Shrenik — your choices create different endings.",
    emoji: "📖",
    color: "#FF9800",
    bg: "linear-gradient(135deg,#1a1000,#2d1c00)",
    age: "8+",
    players: "1",
    available: true,
    value: "Wisdom",
    difficulty: 3,
  },
  {
    id: "temple-builder",
    title: "Temple Builder",
    titleHi: "मंदिर निर्माण",
    desc: "Use Virtue Points (NOT weapons!) to build stunning temples, lotus gardens, bird shelters and meditation halls.",
    emoji: "🕌",
    color: "#FFD700",
    bg: "linear-gradient(135deg,#1a1400,#2d2200)",
    age: "8+",
    players: "1",
    available: true,
    value: "Virtue Building",
    difficulty: 3,
  },
  {
    id: "karma-forest",
    title: "Karma Forest",
    titleHi: "कर्म वन",
    desc: "Watch the forest bloom with every good deed. Trees grow, rivers clear, birds return — or fade with bad choices.",
    emoji: "🌳",
    color: "#388E3C",
    bg: "linear-gradient(135deg,#0a1a00,#142800)",
    age: "5+",
    players: "1",
    available: true,
    value: "Karma & Nature",
    difficulty: 2,
  },
  {
    id: "karma-grid",
    title: "Karma Grid",
    titleHi: "कर्म तिकड़ी",
    desc: "Jain Tic-Tac-Toe! Every tile hides a moral situation. Make wise choices to earn Karma Points — the highest karma score wins!",
    emoji: "🪷",
    color: "#7C4DFF",
    bg: "linear-gradient(135deg,#EDE7F6,#7C4DFF)",
    age: "6+",
    players: "2",
    available: true,
    value: "All Jain Values",
    difficulty: 2,
  },
  {
    id: "word-builder",
    title: "Jain Word Builder",
    titleHi: "जैन शब्द निर्माण",
    desc: "Build Jain words from scrambled letters! Every word reveals its meaning, karma connection, and unlocks wisdom about Jain philosophy.",
    emoji: "📝",
    color: "#9C27B0",
    bg: "linear-gradient(135deg,#F3E5F5,#9C27B0)",
    age: "8+",
    players: "1",
    available: true,
    value: "Knowledge & Wisdom",
    difficulty: 2,
  },
];

export function getGame(id: string) {
  return GAMES.find(g => g.id === id);
}
